#проверка на совершенолетие
# number=int(input("сколько лет тебе"))#возраст
# if number >= 18:
#     print("я должен тебе пиво")
#     product = input("пива или сухареке")
#     if product=="пиво":
#         print("2 рубля")
#         if product=="сухарики":
#             print ("рубель буде?")
# elif number < 18:
#     print ("вон пошёл, не продам")




# print("меню")
# print("сложение\n2. отнимание\n3.умножение\n4.деление\n 5. Выйти ")
# choise= int (input(""))
# a=int(input("введите число a"))
# b=int(input("введите число b"))
# if choise ==1:
#     c=a+b
#     print(c)
# elif choise == 2:
#         c=a-b
#         print(c)
# elif choise == 3:
#     c= a/b
#     print(c)
# elif choise ==4:
#     c=a*b
#     print (c)
# elif choise == 5:
#      print ("СКЕБЕДЕ ТОЛЧОК")
number = int(input("введите число"))

if number > 10 and number <20:
    print ("Введёное число входит в диапазон от 10 до 20")

